### ISSUE TITLE
popup  set_name_agi.py

### ISSUE THREAD

**Issue by zlin143** [OCA/connector-telephony#100]
Hello,

After some setting, now I can directly make a call by using Dial button in the partner form view.

My problem now is to get the partner lead corresponding to the calling party by using phone icon or pop-up . Module base_phone_popup is installed.

Please I need more information about set_name_agi.py and set_name_incoming_timeout.sh to be install in Asterisk server. I would like to know How to make and install the two scripts.

Best regards and thanks for your help.

**Comment by flowersofpepper** [comment]
@zlin143 did you make it work ?
