### ISSUE TITLE
connector-telephony depends on non-OCA addons

### ISSUE THREAD

**Issue by sbidoul** [OCA/connector-telephony#102]
When trying to install the connector-telephony wheel, @lmignon discovered there are missing dependencies.
It is due to a couple of dependencies on `bus_enhanced` and `web_action_request` which are in the anybox repositories: https://github.com/OCA/connector-telephony/blob/a5f1efafa38af194d20a15409ae23dedf00670fb/.travis.yml#L35

I think OCA policy mandates all Odoo addons dependencies to be managed by OCA.

The shortest path to a solution would be for anybox to submit these two modules to OCA.

Any thoughts about this?

**Comment by alexis-via** [comment]
Yes, anybox needs to propose these modules to OCA ! @jssuzanne, please add this to your TODO list :)

**Comment by elicoidal** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:
