### ISSUE TITLE
[8.0] Popup not working when call is UP

### ISSUE THREAD

**Issue by ecino** [OCA/connector-telephony#108]
We installed the asterisk_click2dial module and the phone popup was not working when the call was UP. It works fine when the phone is ringing.

By debugging we saw that we had to change this line :
https://github.com/OCA/connector-telephony/blob/8.0/asterisk_click2dial/asterisk_click2dial.py#L259

to this :  `sip_account in chan.get('Data', '')):`

We have version Asterisk 13.11.2  (xivo 16.12) installed. Is it because we use a wrong version or should this fix be deployed ?

**Comment by alexis-via** [comment]
Yes, this part often needs a little tuning based on the exact version of your Asterisk server and maybe also of your dialplan. It is a bit annoying. I'll try to test at home and see if I have the same issue (I also have a recent Xivo).
