### ISSUE TITLE
[base_phone] Problem in point_of_sale with editing partners

### ISSUE THREAD

**Issue by cvinh** [OCA/connector-telephony#113]
PR for v10.0 here : https://github.com/OCA/connector-telephony/pull/110

**Comment by cvinh** [comment]
PR for 9.0 here : https://github.com/OCA/connector-telephony/pull/111

**Comment by cvinh** [comment]
fixed for v10 in #109

**Comment by alexis-via** [comment]
I added a unitest in my PR #109 to make sure that it doesn't happen any more.
