### ISSUE TITLE
[base_phone] stop all message in chatter

### ISSUE THREAD

**Issue by halgandd** [OCA/connector-telephony#116]
Hi,
if this module is in tree addons, this module stop all messages in chatter.

Regards.

David

**Comment by alexis-via** [comment]
If you use odoo 10, just update your code and it should fix the pb.

**Comment by halgandd** [comment]
Thanks but I use 9.
I has commented this lines on fields.py 

# models.Model.write = write

# models.Model.create = create

But this is not a durable FIX
