### ISSUE TITLE
[base_phone] 10.0 phone field restrictive implementation

### ISSUE THREAD

**Issue by karlis-dreizis** [OCA/connector-telephony#121]
Hello,
i'm working with the current port of base_phone for 10.0.

I find that the current implementation of the phone, tax fields somehow a bit intrusive and have some serious caveats.

1) A phone field definition expects to have a related country and partner field
2) Presentation is done in the ORM layer.
    '+044 34534534' would be stored as '+04434534534', but browsed/read as '+044 3453 5434'

My use case: 
I have a model where I'd would like to have a computed phone field. The model doesn't have the prerequisite _country_ and _partner_ fields. Thus I'm left with using a text field. 

I have to choose whether 
1) to store the number verbatim (searching will require spaces, inconsistent with phone fields in the system )
2) normalize the value by stripping spaces (inconsistent presentation across models)

I feel ideally that the ORM shouldn't be handling presentation and that should be left to the frontend via widgets. 

And in the very least the country and partner fields should be optional. In which case the phone field would fallback to behaving like a regular text field. If the developer would need to enforce a country prefixes he could do so by setting a country_id required=1.

**Comment by karlis-dreizis** [comment]
I'm not quite sure if this was better written in #90. But since its almost half a year old and has an unmeged pr. I did post this issue here. As I feel this topic is worth revisiting.

**Comment by Garamotte** [comment]
Hello,

For the two "partner_field" and "country_field" attributes, looking at the code, I don't think these are actually required (technically). I bet that removing the assert won't make it crash, even if the attributes both have empty values.
If I'm not wrong, if no value is available for any of these two attributes, it will fallback to "don't format the value": https://github.com/OCA/connector-telephony/blob/10.0/base_phone/common.py#L42-L63

About the stored value in database, this is to be discussed. I think that the current behaviour was simpler to implement :)
