### ISSUE TITLE
[9.0] track_visibility is lost

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/connector-telephony#126]
When installing the repo 'connector-telephony' (or testing this repo in runbot) in 9.0, none of the changes in fields that defined with 'track_visibility' are logged in the chatter.

For example, when moving a lead from one stage to another, the message that the stage has changed is not logged in the chatter.

I have not been able to identify the root cause of this issue.

**Comment by Garamotte** [comment]
Hello,

Simply commenting the write method monkey-patch (a single line : https://github.com/OCA/connector-telephony/blob/9.0/base_phone/fields.py#L136) make the track_visibility work again.
It seems that the monkey-patch prevents the `write` method of the `mail.thread` to be called. Probably an issue between monkey-patch and inheritance.

Note that this bug:
- Is the same with the `create` method.
- Appears even if the `base_phone` module is not installed.
- Has been auto-resolved during the v10.0 migration, as we don't need to monkey-patch anymore.

**Comment by Garamotte** [comment]
Oh, just found a PR that fixes this issue : https://github.com/OCA/connector-telephony/pull/123
