### ISSUE TITLE
Problem in the connection to Asterisk

### ISSUE THREAD

**Issue by AdrianJoel** [OCA/connector-telephony#131]
Hi.

I want to integrate Asterisk with Odoo 10. When I defined the Asterisk Server and clicked on "Test Connection to Asterisk" the following message appears: 

Connection Test Sucessfull! Odoo can sucessfully login to the Asterisk Manager Interface.

But, when I clicked on Open Caller icon in the top right corner, the message is: 

FAILURE! Problem in the connection to Asterisk

I am new in this topic. Please help :( 

The manager.conf of my Asterisk Server:

;
; AMI - Asterisk Manager interface
;
; FreePBX needs this to be enabled. Note that if you enable it on a different IP, you need
; to assure that this can't be reached from un-authorized hosts with the ACL settings (permit/deny).
; Also, remember to configure non-default port or IP-addresses in amportal.conf.
; 
; The AMI connection is used both by the portal and the operator's panel in FreePBX.
;
; FreePBX assumes an AMI connection to localhost:5038 by default.
;
[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0
displayconnects=yes ;only effects 1.6+

[admin]
secret = freePBX
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.0
permit = 10.35.2.228/255.255.255.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

#include manager_additional.conf
#include manager_custom.conf

Asterisk Server IP is: 10.35.2.216
Odoo Server: 10.35.2.228

**Comment by alexis-via** [comment]
Please start odoo with --log-level=debug and copy-paste the logs when you click on open caller icon.

**Comment by AdrianJoel** [comment]
@alexis-via I don't know how to do it. Can you tell me what do I have to do?

**Comment by WSMDpro** [comment]
<Asterisk.Manager.Manager connected as ##### to ###########>
{}
odoo.addons.asterisk_click2dial.models.asterisk_server: Result of Status AMI request:
odoo.addons.asterisk_click2dial.models.asterisk_server: {}
{}
odoo.addons.asterisk_click2dial.models.asterisk_server: Calling party number: 'False'


I am working on it and got the same error. Moreover, Dial button is also not visible in v10

**Comment by efernan** [comment]
Hi.

The same problem, Odoo v10:

DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: User's phone: SIP/201
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: Asterisk server: X.X.X.X:5038
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: Result of Status AMI request:
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: {}
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: Calling party number: 'False'

and when I clicked on Open Caller icon:

FAILURE! Problem in the connection to Asterisk

Thanks.

**Comment by WSMDpro** [comment]
We built a PBX connector for Asterisk, just launched this week. Would you like me to get you in touch with the team?

Jamie Funk

On Aug 24, 2017 6:15 AM, efernan <notifications@github.com> wrote:

Hi.

The same problem, Odoo v10:

DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: User's phone: SIP/201
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: Asterisk server: X.X.X.X:5038
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: Result of Status AMI request:
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: {}
DEBUG odoodb odoo.addons.asterisk_click2dial.models.asterisk_server: Calling party number: 'False'

and when I clicked on Open Caller icon:

FAILURE! Problem in the connection to Asterisk

Thanks.

**Comment by efernan** [comment]
Hi.

Yes, how do I it?
Try the new version?

Thanks.

**Comment by WSMDpro** [comment]
What version of Odoo?

Thank you,

Jamie Funk |  jfunk@b2bsoft.com<mailto:jfunk@b2bsoft.com> | Office (212) 742-2301 x732
[cid:image001.jpg@01D2D486.62931C00]

**Comment by efernan** [comment]
Odoo 10.0-20170822 (Versión Community)

Thanks.

**Comment by alexis-via** [comment]
As you can see in the logs, the AMI Status request returns an empty answer. So the problem is on Asterisk's side. I advise you to use network capture tool (tcpdump, wireshark) on port TCP 5038 to get a better understanding of the AMI dialog between Odoo and Asterisk.
