### ISSUE TITLE
asterisk_click2dial shows previous partners phone number

### ISSUE THREAD

**Issue by aaltinisik** [OCA/connector-telephony#14]
On form view of res_partner, 
if you go to next partner by clicking next record button and next partner dont have a phone number in DB Module prints previous partners phone number.

**Comment by aaltinisik** [comment]
This happens in V7.0(OCB)

**Comment by alexis-via** [comment]
@aaltinisik 
Could you try this pull request : https://github.com/OCA/connector-telephony/pull/13
and tell us if it fixes your bug.

**Comment by aaltinisik** [comment]
Yes it fixes the problem. Thak you for very fast solution.
