### ISSUE TITLE
Call history question

### ISSUE THREAD

**Issue by echaritonidis** [OCA/connector-telephony#151]
Hi,

I've [followed the tutorial](http://www.akretion.com/en/products-and-services/openerp-asterisk-voip-connector) and successfully integrated the Asterisk connector module
But my question here is about the history of the calls I'm making
As i understand this is not included by default but I want to ask if there's any module
available for that purpose (log the calls with a view) for odoo 10

Thanks.

**Comment by Vassy** [comment]
Tray to port this https://github.com/mlmconseil/asterisk_log/tree/8.0
