### ISSUE TITLE
base_phone in 10 enterprise  not show link in res.partner

### ISSUE THREAD

**Issue by cor9003** [OCA/connector-telephony#170]
Hello, after install base_phone the phones fields  have been reformat right but in res.partner do not show the link in the phone widget.
In the tree view appears right the link on phone
Note that fax field is also working. Issue is only with phone and mobile fields

![image](https://user-images.githubusercontent.com/6442086/47951688-7e179b00-df64-11e8-928c-9bf67c4d2c46.png)

Thanks in advance for your help

**Comment by mrzingo** [comment]
same here

**Comment by mrzingo** [comment]
Any fix?
