### ISSUE TITLE
Extension does not exist in Odoo 11 with Asterisk 15 using AMI

### ISSUE THREAD

**Issue by santiago1976** [OCA/connector-telephony#172]
Hi,

I'm trying to connect Odoo 11 with asterisk 15 using AMI and connector-telephony addon and if I try to use internal extensions it works fine and Odoo and Asterisk can recognice it.

https://github.com/OCA/connector-telephony

The problem is with external numbers that Odoo, always says the same error about Extension: 'py-Asterisk action failed: Extension does not exist

If I try to dial from Odoo contact using for example this internal number +34 6002 it works, but if I try to dial this external number +34 963 333 333 it fails

This is my extensions.conf

[from-trunk]
;
exten => _6XXX,1,Dial(PJSIP/${EXTEN})
exten => _9XXXXXXXX,2,Dial(PJSIP/${EXTEN})

[from-internal]
;
exten => _6XXX,1,Dial(PJSIP/${EXTEN})
exten => _9XXXXXXXX,2,Dial(PJSIP/${EXTEN})

I've tried with _00349XXXXXXXX, _+349XXXXXXXX, _9., _9XXXXXXXX, etc... and always the same error about Extensions does not exist. I've tried all this settings that appears in this question but it doesn't work:

https://www.odoo.com/es_ES/forum/ayuda-1/question/here-is-the-error-py-asterisk-action-failed-extension-does-not-exist-117343

https://issues.asterisk.org/jira/browse/ASTERISK-22905

Can someone help me?

Thanks

**Comment by pedrobaeza** [comment]
I don't think this is something about Odoo modules, but Asterisk configuration IMO.
