### ISSUE TITLE
asterisk_click2dial - No module named Asterisk

### ISSUE THREAD

**Issue by jayo2004** [OCA/connector-telephony#173]
Odoo 10
I am trying to install click2dial on Odoo 10 but getting below error. I tried `pip install py-asterisk`
and `pip install asterisk`

Unable to install module "asterisk_click2dial" because an external dependency is not met: No module named Asterisk

**Comment by pedrobaeza** [comment]
You should make:
```
sudo pip install py-Asterisk
```
and make sure the library is accessible in your Odoo Python environment.
