### ISSUE TITLE
[11.0] Conflict between crm_phonecall and crm_phone

### ISSUE THREAD

**Issue by altoch** [OCA/connector-telephony#175]
https://github.com/OCA/connector-telephony/tree/11.0
crm_phone

https://github.com/OCA/crm/tree/11.0
crm_phonecall

Updated in the comment below

**Comment by pedrobaeza** [comment]
Which conflict? You have to put details

**Comment by altoch** [comment]
Uppon installation of the modules, all the views related to both applications, that individually work, odoo start throwing errors.

**First error throw on click the crm_phonecall generated menu**

> `Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo11/odoo/api.py", line 687, in call_kw
>     return call_kw_model(method, model, args, kwargs)
>   File "/opt/odoo/odoo11/odoo/api.py", line 672, in call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/models.py", line 1296, in load_views
>     for [v_id, v_type] in views
>   File "/opt/odoo/odoo11/odoo/models.py", line 1296, in <dictcomp>
>     for [v_id, v_type] in views
>   File "/opt/odoo/odoo11/addons/mail/models/mail_thread.py", line 374, in fields_view_get
>     res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
>   File "/opt/odoo/odoo11/odoo/models.py", line 1382, in fields_view_get
>     xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1064, in postprocess_and_fields
>     self.raise_view_error(message, view_id)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 519, in raise_view_error
>     raise ValueError(message)
> ValueError: El campo `tag_ids` no existe
> 
> Contexto del error:
> Vista `CRM - Logged Phone Calls Tree`
> [view_id: 3789, xml_id: crm_phonecall.crm_case_inbound_phone_tree_view, model: crm.phonecall, parent_id: n/a]`


**Second error on click the crm_phone generated menu**

> `IError:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo11/odoo/api.py", line 687, in call_kw
>     return call_kw_model(method, model, args, kwargs)
>   File "/opt/odoo/odoo11/odoo/api.py", line 672, in call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/models.py", line 1296, in load_views
>     for [v_id, v_type] in views
>   File "/opt/odoo/odoo11/odoo/models.py", line 1296, in <dictcomp>
>     for [v_id, v_type] in views
>   File "/opt/odoo/odoo11/addons/mail/models/mail_thread.py", line 374, in fields_view_get
>     res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
>   File "/opt/odoo/odoo11/odoo/models.py", line 1382, in fields_view_get
>     xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1064, in postprocess_and_fields
>     self.raise_view_error(message, view_id)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 519, in raise_view_error
>     raise ValueError(message)
> ValueError: El campo `tag_ids` no existe
> 
> Contexto del error:
> Vista `n/a`
> [view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]`

**Comment by pedrobaeza** [comment]
OK, good to know. Probably the same model name.

**Comment by ruuter** [comment]
This still exists in 12.0 and I confirm that both modules use same model name crm.phonecall. Adding to manifest conflict field seems appropriate.
