### ISSUE TITLE
Wrong Number Conversion

### ISSUE THREAD

**Issue by gokhanerdogdu** [OCA/connector-telephony#176]
Everything is working fine, but the phone number is converted to wrong phone number format when you click on the contact form to call the number. 

Below is the contact form. 

![image](https://user-images.githubusercontent.com/20369981/52740819-f91d3280-2fe4-11e9-8640-563662ebf2ec.png)

The contact address is Turkey and the number is formatted well on the contact form as **+90 216 464 92 01**. 

When the Odoo user (user address is USA) clicks the number, the number sent to the PBX is formatted to **"011902164649201"**. This is very strange. Thus, PBX does not accept the wrongly formatted number. The number should be same as **+90 216 464 92 01**. 

![image](https://user-images.githubusercontent.com/20369981/52740926-38e41a00-2fe5-11e9-838f-58b7972f5cd9.png)

What may be the problem?

**Comment by repka20** [comment]
Try to change your dial patterns in outbound routes. Plugin changed my +7926 number to 8926 and my calls failed. So I fixed it with Asterisk )
