### ISSUE TITLE
Difference to OCA Module CRM_phonecall

### ISSUE THREAD

**Issue by chrizzTs** [OCA/connector-telephony#179]
Hi all,
we are using the module to log phone call manually. During migration to Odoo V.12 I noticed that there is also an OCA module call crm_phonecall https://github.com/OCA/crm/tree/11.0/crm_phonecall

Now I am wondering what the difference between crm_phone module and crm_phonecall is?

Thanks in advance!

**Comment by pedrobaeza** [comment]
`crm_phonecall` adds a model for registering phone calls, and this is for adapting CRM fields to phone format and telephony options.

**Comment by chrizzTs** [comment]
@pedrobaeza I do not agree with this.
I checked on OCA runbot. 
http://3349880-12-0-e77352.runbot2.odoo-community.org

The phone logs are available on this instance:
![image](https://user-images.githubusercontent.com/6087189/53478627-919cc380-3a77-11e9-81a8-0686976b581a.png)
![image](https://user-images.githubusercontent.com/6087189/53478636-99f4fe80-3a77-11e9-8a8b-fafa7de0f954.png)
The module crm_phonecall is not installed on this instance! When uninstalling the module crm_phone the feature of logging calls is gone from the Views. 
Therefore I still think that this module adds these capabilities and is similar to crm_phonecall https://github.com/OCA/crm/tree/11.0/crm_phonecall

**Comment by pedrobaeza** [comment]
Yes, you're right, checking `crm_phone`, @alexis-via introduced that feature silently. For me, that should go outside this module and use the other one, but any way, there's no specific problem. Just don't use the other one for now if you are using this.

**Comment by alexis-via** [comment]
This is a problem of Odoo Community vs Odoo Enterprise.
Let me explain:
in v8, the official "crm" module had an object "crm.phonecall', cf https://github.com/odoo/odoo/blob/8.0/addons/crm/crm_phonecall.py#L30
in v9, this model 'crm.phonecall' was removed from the official 'crm' module, and probably moved to some enterprise module
So I re-introduced the object crm.phonecall in the OCA module "crm_phone".

**Comment by pedrobaeza** [comment]
@alexis-via the issue is that you put the model in `crm_phone` module, and the model is also on `crm_phonecall` module.

**Comment by alexis-via** [comment]
My previous comment was wrong ; I updated it.  The crm.phonecall obj was reintroduced in the OCA module "crm_phone".
There is no crm_phonecall module in the OCA ; it must be an Enterprise module I guess.

**Comment by pedrobaeza** [comment]
@alexis-via see https://github.com/OCA/crm/tree/9.0/crm_phonecall

**Comment by alexis-via** [comment]
Ah, OK, there is also an OCA module doing this !
So I guess we now have the crm.phonecall object in 3 modules: an enterprise module, the OCA module crm_phonecall and the OCA module crm_phone.
It would have been so much easier if Odoo SA just kept it in the 'crm' module...

**Comment by alexis-via** [comment]
The crm.phonecall object was introduced in crm_phone in this commit https://github.com/OCA/connector-telephony/commit/81f01f52a1c4d1ea7b4a179c7428b536929fb99f dated May 24 2016.
The crm.phonecall object was introduced in the crm_phonecall in this commit https://github.com/OCA/crm/pull/131/commits/6c764daa904347d68b98378461273e594afd059c dated January 24 2017.
So it was introduced in OCA/connector-telephony/crm_phone way before it was introduced in OCA/crm/crm_phonecall :)

**Comment by pedrobaeza** [comment]
In this case, the problem in not the dates, but the granularity: force to use the telephony infrastructure only for logging calls is too much. And as said, you introduce that feature silently.

**Comment by alexis-via** [comment]
The sad thing is that Odoo SA removed that crm.phonecall object silently between v8 and v9... let's not foget the real culprit of this mess.

**Comment by pedrobaeza** [comment]
You're right, but now let's go for a unique way in OCA. I propose you to remove the models in v12 in `crm_phone`, and directly depend on `crm_phonecall`.
