### ISSUE TITLE
Is base_phone_popup ready for V12

### ISSUE THREAD

**Issue by ska-ibees** [OCA/connector-telephony#185]
Hi,
It seems that dependencies for base_phone_popup are quite old. Could you please guide as how to install it in V12?

Below is mentioned in manifest file:

The module *web_action_request* can be downloaded with Mercurial:

hg clone http://bitbucket.org/anybox/web_action_request

It depends on 2 other modules, *web_longpolling* and *web_socketio*, that can
be downloaded with this command:

hg clone http://bitbucket.org/anybox/web_socketio

You will find some hints in this documentation :
https://bitbucket.org/anybox/web_action_request

**Comment by pedrobaeza** [comment]
`base_phone_popup` is not migrated yet. That's why it has `'installable': False`.

**Comment by ska-ibees** [comment]
Thanks for the confirmation.
