### ISSUE TITLE
asterisk_click2dial.py: does not trim '(' and ')' from NANPA code format

### ISSUE THREAD

**Issue by alex2grad** [OCA/connector-telephony#19]
function phonenumbers.format_out_of_country_calling_number returns number with '(' and ')' 
example: 1 (416) 222-3456
asterisk_click2dial.py _reformat_number has to trim '(' and ')' 

--- asterisk_click2dial.py.orig 2015-02-03 12:05:36.169608049 -0500
+++ asterisk_click2dial.py      2015-02-03 12:07:32.789779094 -0500
@@ -170,7 +170,7 @@
         assert(country_code), 'Missing country on company'
         _logger.debug('Country code = %s' % country_code)
         to_dial_number = phonenumbers.format_out_of_country_calling_number(
-            parsed_num, country_code.upper()).replace(' ', '').replace('-', '')
-            parsed_num, country_code.upper()).replace(' ', '').replace('-', '').replace('(', '').replace(')', '')
       # Add 'out prefix' to all numbers
       if ast_server.out_prefix:
           _logger.debug('Out prefix = %s' % ast_server.out_prefix)

**Comment by alexis-via** [comment]
This is the PR #16
