### ISSUE TITLE
Asterisk calling previously failed calls

### ISSUE THREAD

**Issue by aaltinisik** [OCA/connector-telephony#20]
Thank you for the module :)

if we make some calls and hangup before connection or do not pickup the phone, 
on next click2call action old number is dialed instead of new one.

So it remembers failed numbers and try to connect you. Is this from asterisk or connector ?

**Comment by alexis-via** [comment]
You should analyse the trafic between asterisk and port (tcp port 5038 by default), and you will know if the problem is on the asterisk side or on the openerp side:

hint:
tcpdump -n -i eth0 -A -s 0 port 5038

**Comment by aaltinisik** [comment]
I am pretty sure it is from openerp side. (from pyAsterisk library) 
directly connected to AMI instead of pyasterisk and no problem.

**Comment by aaltinisik** [comment]
but cannot pinpoint the problem,

**Comment by agutierrezdapda** [comment]
can you test with this code. Work for me.:

```
+++ base_phone/static/src/js/phone_widget.js
@@ -18,6 +18,8 @@
             if (!this.get('effective_readonly')) {
                 this._super();
             } else {
+                // cleanup
+                this.$el.find('#click2dial').off('click');
                 var self = this;
                 var phone_num = this.get('value');
                 //console.log('BASE_PHONE phone_num = %s', phone_num);
```

**Comment by alexis-via** [comment]
@agutierrezdapda I made a PR with your patch and quoted your name in the commit (well, I don't know your real name, so I quoted your github account). Could you make a "+1" on the comment of the PR #52

**Comment by intero-chz** [comment]
Hey guys,

it seems there is the same problem on branch 7.0. Maybe the patch is fixing the problem there, too. I will let you know and create a PR for 7.0 then.

best regards

**Comment by sadasant** [comment]
This also happens in the version available for Odoo 10, and the solution is similar to what has been mentioned: https://github.com/OCA/connector-telephony/pull/157
