### ISSUE TITLE
how to make sure that I stay in contacts and not get redirected to discuss

### ISSUE THREAD

**Issue by f1-outsourcing** [OCA/connector-telephony#228]
How to make sure that I stay in contacts and not get redirected to discuss.

odoo12

**Comment by Cristian-Rguez** [comment]
Hi, I think a better solution that worked for me would be

```js
dial.click(function(evt) {
    evt.preventDefault();
    self.click2dial(phone_num);
});
```
This prevents the page from reloading to the same url.
Tested in Firefox and Chrome
