### ISSUE TITLE
odoo12: remove depdency phone_validation so this can be removed.

### ISSUE THREAD

**Issue by f1-outsourcing** [OCA/connector-telephony#232]
phone_validation is useless.

https://github.com/odoo/odoo/issues/62227

**Comment by Yenthe666** [comment]
Lol.. @pedrobaeza 🤣

**Comment by f1-outsourcing** [comment]
You should read the comment[1], this module is not properly designed in my opinion. It allows the storing of +xx xxxxxx numbers and xxxxxxxx numbers, which is not consistent. Better would be to store only one format +xx xxxxxxxx, that is at least consistent. Furthermore what does it actually validate? I cannot imagine you know all the phone number patterns of all countries in the world. Best is just leave it up to the user.

[1]
https://github.com/odoo/odoo/issues/62227#issuecomment-732953361
