### ISSUE TITLE
O módulo "base_phone" não pode ser instalado porque uma dependência externa não foi encontrada: Python library not installed: phonenumbers

### ISSUE THREAD

**Issue by Guilhermealves20101999** [OCA/connector-telephony#257]
Está dando essa mensagem sendo que ja fiz a instalação via CMD, "pip install phonenumbers", como consigo resolver

**Comment by pedrobaeza** [comment]
Please install such Python library in your Odoo environment. Closing as no issue in the module, but deployment one.
