### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by GiuTav** [OCA/connector-telephony#264]
HI,
I created the Italian translation of the module if you want to insert it directly in the git I leave you the .po file.
The translation was carried out using the odoo tool for exporting the texts to be translated.
If you have files with multiple fields to translate do not hesitate to pass them to me, I will translate them and upload.
Thank you and good day.

[it.zip](https://github.com/OCA/connector-telephony/files/7880254/it.zip)

**Comment by pedrobaeza** [comment]
Please see https://odoo-community.org/page/translate
