### ISSUE TITLE
hiiii, i'm trying to configure base_phone_popup module but i can't found the dependencies modules like   web_action_request, web_socketio and  web_longpolling . It looks like the repository was deleted from  bitbucket. Where can i found these modules please???

### ISSUE THREAD

**Issue by bouthainaayadi** [OCA/connector-telephony#269]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by alexis-via** [comment]
Starting from v12, base_phone_popup uses web_notify, so you should not have to search from the old modules web_action_request, etc...
