### ISSUE TITLE
asterisk_click2dial: AMI -> ARI

### ISSUE THREAD

**Issue by alexis-via** [OCA/connector-telephony#276]
For the module asterisk_click2dial, we should switch from AMI to ARI. That will remove dependency on py-Asterisk and we'll use lib requests to perform the ARI requests.

If you disagree with this change, please comment and explain.

**Comment by alexis-via** [comment]
I developped a proto on my laptop for click2dial ; it works well, and I think it simplifies the code. I still need to update the code of _get_calling_number()

**Comment by alexis-via** [comment]
I have a first working version with _get_calling_number(). So I can now confirm that AMI can be fully replaced by ARI in the module asterisk_click2dial while keeping all the features of the module.

**Comment by alexis-via** [comment]
I now need to cleanup the code, commit and make a PR. Probably this week-end.

**Comment by alex2grad** [comment]
I willing to test if the PR is ready?

**Comment by alexis-via** [comment]
It has already been merged in this PR https://github.com/OCA/connector-telephony/pull/292
