### ISSUE TITLE
TypeError: Model 'phone.validation.mixin' does not exist in registry.

### ISSUE THREAD

**Issue by halie412** [OCA/connector-telephony#278]
Hi i´m new on odoo and also trying to use OCA modules, i try to install Asterisk connector (https://apps.odoo.com/apps/modules/14.0/asterisk_click2dial/)

But i get this error:
RPC_ERROR
Odoo Server Error

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1578, in _serve_db
>     return service_model.retrying(self._serve_ir_http, self.env)
>   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
>     result = func()
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1607, in _serve_ir_http
>     response = self.dispatcher.dispatch(rule.endpoint, args)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1804, in dispatch
>     result = self.request.registry['ir.http']._dispatch(endpoint)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 140, in _dispatch
>     result = endpoint(**request.params)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in route_wrapper
>     result = endpoint(self, *args, **params_ok)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
>     action = self._call_kw(model, method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-74>", line 2, in button_immediate_install
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 490, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 614, in _button_immediate_function
>     registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "<decorator-gen-14>", line 2, in new
>   File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
>     return func(inst, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 91, in new
>     odoo.modules.load_modules(registry, force_demo, status, update_module)
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 482, in load_modules
>     processed_modules += load_marked_modules(cr, graph,
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 371, in load_marked_modules
>     loaded, processed = load_module_graph(
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 196, in load_module_graph
>     model_names = registry.load(cr, package)
>   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 241, in load
>     model = cls._build_model(self, cr)
>   File "/usr/lib/python3/dist-packages/odoo/models.py", line 643, in _build_model
>     raise TypeError("Model %r does not exist in registry." % name)
> TypeError: Model 'phone.validation.mixin' does not exist in registry.

I check and phone_validation is already installed.

What i can do for use the module?

**PD:** I use Odoo Server 16.0-20221128, on VPS running Debian 11

**Comment by pedrobaeza** [comment]
The module is not yet migrated to v16.
