### ISSUE TITLE
Pop Up Window for incoming calls with Asterisk2Dial Odoo V14

### ISSUE THREAD

**Issue by milocheri** [OCA/connector-telephony#291]
Hello, i just setup Click2Dial , i already set the settings, and i can make outbound calls directly from Odoo, however, for incoming calls nothing happens, i dont see any popup window,  also if i click in the icon on the left, i getan error message saying "calling party number not retrieved from pbx or pbx unreachable by odoo"

![image](https://user-images.githubusercontent.com/123685674/214954211-c7f87b44-cb43-4e38-8d54-a2642f101b2f.png)

For the setup, i follow this video, wich is very friendly tu understand the setup

https://www.youtube.com/watch?v=CTOjvh5ypf0&ab_channel=MULTISOLUCIONESNICARAGUA

**Comment by moon-fox** [comment]
@milocheri hi there, can you show me how you setup click2dial with asterisk?
And I also facing the same problem as you

**Comment by milocheri** [comment]
> @milocheri hi there, can you show me how you setup click2dial with asterisk? And I also facing the same problem as you

i did it just as the video shows, go to the minute 19:11

**Comment by moon-fox** [comment]
@milocheri how do you configure click2dial to receive the incoming calls?

**Comment by milocheri** [comment]
> @milocheri how do you configure click2dial to receive the incoming calls?

that's exactly what i'm looking to make it work inside Odoo, it doesn works

**Comment by moon-fox** [comment]
@milocheri I've followed the instructions from this website and it works https://miblogtecnico.wordpress.com/tag/asterisk-click2dial/

but when someone calls an extension associated with the odoo's user, you have to click the phone icon and then the calling party's information will show up.
