### ISSUE TITLE
Would you accept a PR to add ``requirements.txt`` ?

### ISSUE THREAD

**Issue by vaab** [OCA/connector-telephony#30]
I see that you are using `external_dependencies` in `__openerp__.py`. For purely personal reasons, I prefer `requirements.txt` (that gets installed automatically with one of our scripts.).

However, it seems that odoo itself uses `requirements.txt` and it could make sense for you to have this. I could even make a PR that would avoid duplication of this information by sourcing `requirements.txt` in your actual `__openerp__.py`.

This would basically add a `requirements.txt` at the root of each modules that have a `external_dependencies` in their `__openerp__.py`.

**Comment by pedrobaeza** [comment]
@gurneyalex, opinion on this?

**Comment by gurneyalex** [comment]
@pedrobaeza @vaab :+1:

**Comment by vaab** [comment]
The PR is on #33
