### ISSUE TITLE
asterisk_click2dial.py strips down extensions

### ISSUE THREAD

**Issue by bynicolas** [OCA/connector-telephony#32]
Normally, extensions would be written with a comma "," witch is interpreted as a pause
The check should avoid stripping down what's after the coma and keep it instead for dialling out.

I realize this is also an Odoo field limitation, maybe the better solution would be to have an extra input box for the extension and add a coma when dialling out for the pause

**Comment by alexis-via** [comment]
We need to figure out how extensions are managed by the "phonenumbers" python lib.
