### ISSUE TITLE
Unable to connect to Openerp 7.0 When SSL is enabled

### ISSUE THREAD

**Issue by senolsun** [OCA/connector-telephony#43]
the module is unable to connect to our openerp 7.0 implementation that uses nginx reverse proxy for SSL. XML-RPM is bind to 127.0.0.1 and not accepting other connections on other interfaces. Secure XML-RPC is no longer supported by Openerp as you may be aware. What is the solution to use with a server that is behind nginx?

**Comment by pedrobaeza** [comment]
Why are you opening this question as an issue and in a project that is not related?

Please use the corresponding Odoo forum.
