### ISSUE TITLE
Error reported on app.odoo.com

### ISSUE THREAD

**Issue by yvaucher** [OCA/connector-telephony#45]
2 people are reporting

Here is the error message: 'NoneType' object has no attribute 'Manager'

https://apps.openerp.com/apps/modules/8.0/asterisk_click2dial/

BTW: We might need to add a link on each `README.rst` to point where to make bug report!

EDIT: added a pull request there to improve template https://github.com/OCA/maintainer-tools/pull/59

**Comment by alexis-via** [comment]
I think they just forgot to install the lib py-Asterisk

**Comment by yvaucher** [comment]
Shouldn't external-dependencies in `__openerp__.py` already prevent this error ?

**Comment by AidenAndrews** [comment]
I just installed the plugin i got this error first turns out on ubuntu you need to copy the python libraries py-asterisk and py-phonenumbers to odoo's root directory

**Comment by AidenAndrews** [comment]
On ubuntu pip install didn't work properly. instead use pip install git+https://(github url of dependancy).

**Comment by fr33dz** [comment]
wget https://pypi.python.org/packages/source/p/phonenumbers/phonenumbers-7.0.9.tar.gz
python setup.py

wget https://pypi.python.org/packages/source/p/py-Asterisk/py-Asterisk-0.5.5.tar.gz
python setup.py
