### ISSUE TITLE
Pop-up Error

### ISSUE THREAD

**Issue by fr33dz** [OCA/connector-telephony#56]
Dear Alexis,

I have a problem when i try to make a call in odoo,
I hope to help me.

Echec du clic to dial avec Asterisk.
Voilà l'erreur : 'py-Asterisk action failed: Originate failed'

Click to dial with Asterisk failed.
Here is the error: 'py-Asterisk action failed: Originate failed'

**Comment by christophdb** [comment]
Hi fr33dz,
is the connection test in odoo successful? If yes than I think the user in the asterisk machine does not have enough rights to originate a call. Can you post your entry in the manager.conf of the asterisk telephony system?
Best regards
Christoph

**Comment by mbmannubisht** [comment]
Hi

Hope you are doing well.
I am facing the same issue kindly help me how to fix it

**Comment by mbmannubisht** [comment]
Hi 

Hope you are doing well.

Please share your views

**Comment by alexis-via** [comment]
Please post here the debug logs of Odoo (--log-level=debug on odoo command line)
