### ISSUE TITLE
Labels to sync

### ISSUE THREAD

**Issue by yvaucher** [OCA/connector-telephony#6]

**Comment by alexis-via** [comment]
@yvaucher What do you mean exactly by "Labels to sync" ?

**Comment by yvaucher** [comment]
@alexis-via some issue labels are missing like `need fixing` `work in progress`

Here is the tool to use
https://github.com/OCA/maintainers-tools/blob/master/tools/set_repo_labels.py

**Comment by yvaucher** [comment]
This was done. I close this
