### ISSUE TITLE
RFC 9.0: store and display phone numbers

### ISSUE THREAD

**Issue by alexis-via** [OCA/connector-telephony#90]
This is not a bug report, but a request for comment. I'd like to collect your opinion about what you consider as the best approch to store and display phone numbers in Odoo. Let's me describe 4 solutions:

a) the current implementation in odoo v7 and v8: the phone numbers are stored in E.164 format, for example "+33141981242". As this is difficult to read, the base_phone module provides a "phone" widget which uses the phonenumbers JS lib to convert it on the fly to international format with spaces. This widget currently works on form and tree view, but not on kanban. It also inherits the formatLang() method which is used in aeroo reports, but I don't think this method is used in qweb reports, so I don't know if it currently works to have readable phone numbers in qweb reports.
Advantage:
- very easy to lookup a phone number on incoming call ; we simply use the ORM search method that way: self.search([('phone', '=like', '%' + end_incoming_phone_num)])

Drawback:
- requires a JS lib for display -> add client-side computing
- we should inherit EVERY display of the field: form, tree, kanban, reports, etc... which is a lot of not-so-easy code to maintain.

b) the "sanitized" solution. In Odoo v9, on res.partner.bank, we have 2 fields: acc_number and sanitized_acc_number, cf https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_bank.py#L60
We could use the same approach: sanitized_phone would be a computed store=True field that stores the field in E.164 format ; this field would not be visible in the views. When we lookup a number on an incoming phone call, we would use the sanitized_phone field. The regular phone field would have the readable version of the phone number that is displayed in views and reports.
Advantage:
- 2 fields for 2 different use case

Drawback:
- we double the number of phone fields on each object that has phone numbers (partner, lead, employees, ...)
- when we convert a phone number to E.164, we don't just remove spaces ; we parse the number taking the country into account, and this parsing can sometime be wrong (because the country is wrong for example). So, if the sanitized_phone field is not displayed in view, the user won't see that there is a problem in the E.164 version of the field. But, to solve it, we could continue to inherit write/create so that the regular "phone" field contains the number in international format with spaces and sanitized_phone contains the number in E.164 format ; that way, if there is a problem in the parsing of the phone number, the user will "see" it in the regular "phone" field.

c) Instead of storing the phone fields in E.164 format, we would store the phone fields in international format with the spaces, for example +33 1 41 98 12 42. When we lookup a phone number for an incoming call, we would use cr.execute(SELECT id from res_partner where replace(replace(phone, ' ', ''), '-', '') like '%' + end_incoming_phone_num)
Advantage:
- we can display the phone field as-is in form/tree/kanban views and in reports. No need to use the phonenumbers JS lib. No client-side processing.

Drawback:
- we by-pass the ORM when we search the phone number on incoming calls -> not as easy to search for a phone number.

d) develop a new "Phone" field (solution suggested by @sebastienbeau)

```
phone = fields.Phone(string='Fixed Phone')
mobile = fields.Phone(string='Mobile Phone')
```

This special field would store the field in E.164 format in DB and use the phonenumbers python lib to convert it to international format with spaces when reading/browing it.
Advantage: 
- we can display the phone field as-is in form/tree/kanban views and in reports. No need to use the phonenumbers JS lib. No client-side processing.

Drawback:
- requires more technical knowledge to develop it
- still need to confirm that it's technically possible.

Please tell me what you consider the best solution and explain why. We could use the port to v9 currently in progress in this PR https://github.com/OCA/connector-telephony/pull/88 to switch from solution a) to another solution.

**Comment by alexis-via** [comment]
Here is my own opinion:

I don't have experience developping a new type of field, so I don't know if solution d) would work.

I like option b) with the 2 fields:
- "phone" storing the number in international format with spaces (using the phonenumbers python lib) via an inherit of write/create like and displayed in the views and reports
- "phone_sanitized" storing the number in E.164 format (using the same lib) and would not be visible in the interface ; "phone_sanitized" would be used to match the phone number on incoming calls.

The main drawback of solution b) is that it's a bit "heavy" for each object that has phone fields because you have to both inherit write/create AND define new sanitized fields.

**Comment by ivantodorovich** [comment]
I like option **b)** because it seems a 'clean' solution that does not invade the user in any way. Also, we could easily remove other non-numeric characters beside spaces, like `()[]-`. It's very common (at least in my country) to store phone numbers like this `0800-444-1234` or `(011) 1234-5678`

If you are worried about the country code being wrong maybe we can develop a phone widget that enforces the user to select the country code, just like Google does for Inbox/Gmail:

Or just live with it.. it doesn't seem that big of a deal, all considering.

![image](https://cloud.githubusercontent.com/assets/1914185/15659172/c4489ab2-269c-11e6-9208-313a43aa5dbd.png)

![image](https://cloud.githubusercontent.com/assets/1914185/15659173/c7f05ee8-269c-11e6-8237-d7abd20b5efc.png)

**Comment by alexis-via** [comment]
@invitu @jmalinens @alnslang As you are familiar with the code base of connector-telephony, I'd like to have your opinion on this.

**Comment by jmalinens** [comment]
I am for option b) too.

**Comment by sla-subteno-it** [comment]
I like option d) and b). But I think the solution d) should be develop by Odoo not OCA. Maybe ask to Odoo for the next version (v10) ?
So for v9, the option b) seems a clean solution.

**Comment by cvinh** [comment]
I agree.
option d) should be in the core.
option b) seems to be closer to Odoo and does not bypass the orm
+1 for option b

**Comment by gdgellatly** [comment]
I prefer option d. However there is the issue of preexisting field
definitions. So you could take advantage of adding an extra kwarg and
overriding get and set methods of char field when for example phone =true.
That way you won't break multiple modifications.

It really isn't much different to how date fields work to implement and
indeed could support multiple representations in a similar way to date.

**Comment by alexis-via** [comment]
@sebastienbeau has investigated option d) and developed a proto available here: https://github.com/akretion/server-tools/blob/9.0-phone-field/base_phone_fields/ You can have a look at the code of fields.py ; it's not so complex... the only small drawback is that it requires a monkey-patching of write.

As options d) seems less complex than I thought, I am planning to implement option d in the base_phone module, unless some of you have strong arguments against it.

P.S. : don't worry, the final version will be in connector-telephony and not server-tools.

**Comment by alexis-via** [comment]
For me, the only thing that could prevent us from choosing option d) now is the impact on performance on read/browse requests.

**Comment by cvinh** [comment]
As Odoo SA has a voip module in enterprise version, I think they should be interested in that. Maybe you could do a PR against odoo's master and do a backport module for OCA... ?

**Comment by ivantodorovich** [comment]
> invitu commented 5 hours ago
> As Odoo SA has a voip module in enterprise version, I think they should be interested in that. Maybe you could do a PR against odoo's master and do a backport module for OCA... ?

+1 :+1: 

You could even go bigger and propose a patch to make it easier to add new fields without performance loss. 

That way, custom modules could easily add new fields with custom validations and behaviours (Phone, Emails, Addresses, Percentage, Geolocations, and such..) 
I think odoo community could benefict from this.

**Comment by alexis-via** [comment]
I already have 19 open PR on odoo, and there is a total of 923 open PRs on Odoo... and most of them never had any attention from the editor. So I won't propose any PR against master on this particular topic, but feel free to do it if you are motivated.

**Comment by ivantodorovich** [comment]
> alexis-via commented 5 hours ago
> I already have 19 open PR on odoo, and there is a total of 923 open PRs on Odoo... and most of them never had any attention from the editor. So I won't propose any PR against master on this particular topic, but feel free to do it if you are motivated.

It's a shame they don't pay much attention to the community contributions :-1: 
I wonder if, at some point, should't we fork odoo itself and make it evolve faster than they do, as a trully open governance project.

Anyway.. we should test the performance loss very carefully, then.

**Comment by alexis-via** [comment]
With the help of @sebastienbeau, I started to implement solution d), as discussed in this thread. The changes are in my PR to port to v9 https://github.com/OCA/connector-telephony/pull/88
A lot of things are still broken, but the basic things are working (create/write/browse and the basic phone/fax widget)

**Comment by alexis-via** [comment]
This RFC has been implemented in v9 and then ported to v10, so let's close it.
