### ISSUE TITLE
Reformat Phonenumbers Error with Odoo 9c

### ISSUE THREAD

**Issue by christophdb** [OCA/connector-telephony#92]
Hi, 
I installed the newest commit of the akretion connector for odoo 9 community version. Outgoing calls are working perfectly and also the identification of known numbers. It the numbers is known the partner is opened correctly.

There is one error with unknown numbers. As soon as I click on the phone the identify the number I receive the error:

<code>
File "/opt/odoo/custom/addons/telephony/base_phone/wizard/number_not_found.py", line 62, in default_get
    convert = self.evn['res.partner']._reformat_phonenumbers_create(
AttributeError: 'res.partner' object has no attribute '_reformat_phonenumbers_create'
</code>

Any help is appreciated.
Best regards
Christoph

**Comment by christophdb** [comment]
Might it be the case that within the newest tree the base_phone.py is missing? 
I was searching the different py files for the function reformat_phonenumbers_create but I couldn't find it.

**Comment by christophdb** [comment]
Hi everybody,
(the tree I used: https://github.com/OCA/connector-telephony/tree/df392ae1af939488628a509e4de1a7ca28d58a02)

I solved the problem by copying the base_phone.py to the folder "base_phone" and to add this file to the _init.py__ "from . import base_phone". Then I restarted the server and then the popup for an unknown number was working.

Best regards
Christoph

**Comment by alexis-via** [comment]
OK, I see the cause of the pb ; I'll fix it very soon.
